# Generated by Django 5.2.16 on 2026-07-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon', max_length=50, null=True),
        ),
    ]
