# Generated by Django 5.2.16 on 2026-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='menu/'),
        ),
    ]
