# Generated by Django 5.2.16 on 2026-08-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
